version: 2.1
orbs:
  openjdk-install: cloudesire/openjdk-install@1.2.3
jobs:
  build:
    docker:
      - image: alpine:3.15 # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            ./gradlew clean build

  build-image:
    docker:
      - image: alpine:3.15 # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: The First Step
          command: |
            docker 
            echo 'This is the delivery pipeline'