version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15 # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'


  build-image:
    docker:
      - image: alpine:3.15 # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run:
          name: The First Step
          command: |
            docker 
            echo 'This is the delivery pipeline'

  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: csv-reader:latest
          dockerfile: /csv-reader/etc/Dockerfile

workflows:
  example-workflow:
    jobs:
      - example-job